# Generated by Django 4.0.4 on 2022-05-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculatorapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculation',
            name='calc_string',
        ),
        migrations.AddField(
            model_name='calculation',
            name='calc_results',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AddField(
            model_name='calculation',
            name='calc_values',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
